---
# Set up Docker and get our app running on a newly-initialised Droplet.
# (See `new_droplet.yml` for the create-new-droplet Playbook.)
#
# Ensure that:
# 1. The latest version of Python's `pip` utility is installed;
# 2. Install the `docker-py` (**NOT** `dopy`!) Python module. This will be used
#    by the `docker` Ansible module;
# 3. The desired Docker image has been pulled if not already on the remote;
# 4. The desired Docker image has been started (on the remote);
# 5. Content is available from the Web server hosted by the named Droplet;
#
# KNOWN TBDs:
# 1. The desired Floating IP already exists;
# 2. The desired Floating IP is reassigned to the named Droplet;
# 3. Content is available from the Web server addressed by the Floating IP.

- name: Get a Docker image up and running on a newly-initialised Droplet
  hosts: provisioned
  remote_user: '{{ droplet_user_name }}'
  vars_files:
    - secret
    - docker_app
    - running_droplet_details

  tasks:
    - name: Ensure pip is upgraded
      pip:
        name: pip
        state: latest

    - name: Install docker-py via pip
      pip:
        name: docker-py
        state: present

    # FIXME: Don't hardcode image name! Use an extra var instead
    - name: pull Docker image
      docker_image:
        state: present
        name: "{{ docker_hub_user }}/{{ app_image_tag }}"

    # FIXME: Don't hardcode environment variables; those should be extras too
    - name: ensure Docker container is running
      docker_container:
        state: started
        # interactive: yes
        # tty: yes
        # auto_remove: yes
        detach: yes
        exposed_ports: "80"
        memory: '{{ docker_container_memory }}'
        published_ports: "80:80"
        env:
          REACT_APP_GIT_HASH_FULL: '{{ git_hash_full }}'
          REACT_APP_GIT_HASH_SHORT: '{{ git_hash_short }}'
          REACT_APP_IMAGE_TAG: '{{ app_image_tag }}'
          DOCKER_HUB_USER: '{{ docker_hub_user }}'
        image: "{{ docker_hub_user }}/{{ app_image_tag }}"
        name: '{{ docker_container_name }}'

    - name: get Droplet IP address
      shell: ifconfig eth0 | grep 'inet addr' | awk '{printf("%s\n", $2); }' | cut -f 2 -d ':'
      changed_when: false
      register: droplet_ip
    - name: debugging
      debug: var=droplet_ip

    - name: ensure content is available from the Droplet IP directly
      uri:
        url: "http://{{ droplet_ip.stdout }}/"
        return_content: yes
      register: droplet_page

    - debug: msg="droplet_page.etag is {{ droplet_page.etag }}"

    # - name: ensure Floating IP is assigned to target droplet
    #   digital_ocean_floating_ip:
    #     ip: '{{ floating_ip }}'
    #     droplet_id: '{{ do_id }}'
    #     oauth_token: '{{ do_token }}'

    # - name: ensure content is available from the Floating IP host
    #   uri:
    #     url: "http://{{ floating_ip }}/"
    #     return_content: yes
    #   register: floating_page
    # - debug: var=floating_page.etag

    # - name: verify Floating IP produces same content as Droplet IP
    #   assert:
    #     that:
    #       - "floating_page.etag == droplet_page.etag"

    - name: Create final droplet tag if not already created
      delegate_to: 127.0.0.1
      digital_ocean_tag:
        name: '{{ final_tag_name }}'
        state: present

    - name: Add final droplet tag
      delegate_to: 127.0.0.1
      digital_ocean_tag:
        resource_id: '{{ do_id }}'
        name: '{{ final_tag_name }}'
        state: present

    - name: Untag droplet as provisioned
      delegate_to: 127.0.0.1
      digital_ocean_tag:
        resource_id: '{{ do_id }}'
        name: provisioned
        state: absent
