# Run this Playbook with the command line
#     ansible-playbook remove_droplet.yml -e droplet_id=$DROPLET_ID --vault-password=./.vault-password
#
# with a suitable value replacing `$DROPLET_ID`, of course. Note that running
# this Playbook with an invalid or illegal value for `$DROPLET_ID` will fail the
# first task.
#
# Notes:
# 1. To delete a Droplet using the `digital_ocean` module, Ansible must be at
#    least at Version 2.4.0.0.
# 2. There appears to be no stock Ansible module that will power down a Droplet.
#    However, at least under Ansible 2.4.0.0, a running Droplet may be deleted.
#    With great power comes great danger. You Have Been Warned.
---
- name: Shut down and remove a DigitalOcean Droplet
  hosts: localhost
  vars_files:
    - secret.vault.yml
  vars:
    ssh_key_ids: ['{{ do_ssh_key_id }}']
  tasks:
    - name: Verify that Droplet ID variable has been set
      fail: msg="Please define a 'droplet_id' variable with the numeric Droplet ID"
      when: "droplet_id is not defined"

    - name: Remove Droplet
      digital_ocean:
        command: droplet
        id: '{{ droplet_id }}'
        state: absent
        ssh_key_ids: '{{ ssh_key_ids }}'
